name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH (원격 접속)로 EC2 에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            # Check if the directory exists
            if [ ! -d "/home/ubuntu/github-action-server" ]; then
              # If not, clone the repository
              git clone https://github.com/yeoic/github-action-server.git /home/ubuntu/github-action-server
            else
              # If it exists, pull the latest changes
              cd /home/ubuntu/github-action-server
              git pull origin main
            fi
            
            # Continue with the build and deployment process
            cd /home/ubuntu/github-action-server
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &